site_name: Kustomz Mod Shop
site_description: Premium Mod Services for CSR2
theme:
  name: material
  palette:
    scheme: slate
  logo: assets/logo-placeholder.txt
extra_css:
  - assets/css/kustomz.css
nav:
  - Home: index.md
  - Mod Services: mod-services.md
  - Customer Portal: customer-portal.md
  - Kustomz Bot: bot.md
  - Legal:
     - Disclaimer: disclaimer.md
     - Terms of Service: terms.md
     - Privacy Policy: privacy.md
     - Acceptable Use Policy: acceptable-use.md
     - Data Deletion Policy: data-deletion.md
